### PR TITLE
Make install.sh check if it's being run as root

### PR DESCRIPTION
**Pull request by virtualdxs**
... and exit if so to avoid a huge headache when you get 403 on index.php

Issue #36 is most likely a result of this.

### CODE REVIEW

**Comment by argilo** [comment]
When I run this on Ubuntu I get an error:
```
$ sh install.sh
install.sh: 10: [: Illegal number:
```
I was able to fix that by changing the if statement to:
```
if [ "$(id -u)" = "0" ]
```
Does that work on the Pi as well? I'm not at home to test it right now.

**Comment by virtualdxs** [comment]
Interesting. I'll test it on the Pi in a half an hour. Meanwhile I'll commit that change to the branch on my fork.

**Comment by virtualdxs** [comment]
Yeah, it works like that. Interesting.

**Comment by urlgrey** [comment]
Thanks for the PR!

**Pull request merged**
